import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.169.0/build/three.module.js';
import loadMujoco from './9-mujoco.js';
import {LowLevel,getState,clip} from './5-controller.mjs';
const $=s=>document.querySelector(s),canvas=$('#scene'),container=canvas.parentElement,mode=$('#mode'),mission=$('#mission');mode.textContent='LOADING PHYSICS';mission.textContent='Loading the original campus and robot model. First load downloads about 15 MB.';
try{
const [mj,P,xml]=await Promise.all([loadMujoco({locateFile:()=>new URL("./2-mujoco.wasm",import.meta.url).href}),fetch('./10-geometry.json',{cache:'no-store'}).then(r=>r.json()),fetch('./3-scene.xml',{cache:'no-store'}).then(r=>r.text())]);const m=mj.MjModel.from_xml_string(xml),d=new mj.MjData(m);mj.mj_forward(m,d);const ll=new LowLevel(P),ids=P.ids;
const state={v:0,yaw:0,hatch:false,distance:0,paused:false,camera:'follow',simTime:0,actualSpeed:0};window.zebraState=state;
const scene=new THREE.Scene();scene.background=new THREE.Color('#b6d8e7');scene.fog=new THREE.Fog('#b6d8e7',75,200);const root=new THREE.Group();root.rotation.x=-Math.PI/2;scene.add(root);const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;const camera=new THREE.PerspectiveCamera(48,1,.03,300);scene.add(new THREE.HemisphereLight(0xffffff,0x688468,2));const sun=new THREE.DirectionalLight(0xffecd6,2.5);sun.position.set(-4,25,10);scene.add(sun);
const visible=[];const tmp=new THREE.Matrix4();for(const g of P.geoms){if(g.group===3||g.rgba[3]===0)continue;let geometry;const sz=g.size;
if(g.type===0)geometry=new THREE.PlaneGeometry(Math.max(sz[0]*2,160),Math.max(sz[1]*2,160));
else if(g.type===2)geometry=new THREE.SphereGeometry(sz[0],24,18);
else if(g.type===3){geometry=new THREE.CapsuleGeometry(sz[0],2*sz[1],6,12);geometry.rotateX(Math.PI/2)}
else if(g.type===4){geometry=new THREE.SphereGeometry(1,24,16);geometry.scale(...sz)}
else if(g.type===5){geometry=new THREE.CylinderGeometry(sz[0],sz[0],2*sz[1],24);geometry.rotateX(Math.PI/2)}
else if(g.type===6)geometry=new THREE.BoxGeometry(sz[0]*2,sz[1]*2,sz[2]*2);
else if(g.type===7){const mesh=P.meshes[g.mesh];geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(mesh.v.flat(),3));geometry.setIndex(mesh.f.flat());geometry.computeVertexNormals()}else continue;
const material=new THREE.MeshStandardMaterial({color:new THREE.Color(...g.rgba.slice(0,3)),roughness:.65,side:g.type===0?THREE.DoubleSide:THREE.FrontSide,transparent:false,opacity:1});if(g.name?.startsWith('eye')){material.emissive.copy(material.color);material.emissiveIntensity=2}const obj=new THREE.Mesh(geometry,material);obj.receiveShadow=true;root.add(obj);visible.push([g.id,obj])}
function renderGeom(){for(const [id,obj]of visible){const r=d.geom_xmat,p=d.geom_xpos,k=id*9;tmp.set(r[k],r[k+1],r[k+2],0,r[k+3],r[k+4],r[k+5],0,r[k+6],r[k+7],r[k+8],0,0,0,0,1);obj.quaternion.setFromRotationMatrix(tmp);obj.position.set(p[id*3],p[id*3+1],p[id*3+2])}}
const keys=new Set();let last=performance.now(),acc=0,elapsed=0,previous=getState(m,d,ids).pos;
function stop(){state.v=0;state.yaw=0;keys.clear();mission.textContent='Speed command zero. The original controller brakes the sphere.'}
function hatch(){if(Math.abs(getState(m,d,ids).v)>.05){mission.textContent='Stop before opening the hatch.';return}state.hatch=!state.hatch;$('#hatch').textContent=state.hatch?'Close hatch':'Open hatch';mission.textContent=state.hatch?'Hatch open. Close it before driving.':'Hatch closed.'}
$('#stop').onclick=stop;$('#hatch').onclick=hatch;$('#auto').textContent='Pause physics';$('#auto').onclick=()=>{state.paused=!state.paused;$('#auto').textContent=state.paused?'Resume physics':'Pause physics';$('#auto').classList.toggle('active',state.paused)};$('#reset').onclick=()=>{mj.mj_resetData(m,d);mj.mj_forward(m,d);ll.reset();Object.assign(state,{v:0,yaw:0,hatch:false,distance:0,paused:false,simTime:0});keys.clear();previous=getState(m,d,ids).pos;acc=0;$('#hatch').textContent='Open hatch';$('#auto').textContent='Pause physics';mission.textContent='Original campus reset. Hold the arrows to drive.'};
for(const view of ['follow','map'])$('#'+view).onclick=()=>{state.camera=view;for(const b of ['follow','map'])$('#'+b).classList.toggle('active',b===view)};
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key)){e.preventDefault();if(e.key===' ')stop();else keys.add(e.key)}if(e.key.toLowerCase()==='o'&&!e.repeat)hatch()});addEventListener('keyup',e=>keys.delete(e.key));addEventListener('blur',()=>{stop();state.paused=true;$('#auto').textContent='Resume physics'});document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();state.paused=true;$('#auto').textContent='Resume physics'}});document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key)};for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys.delete(b.dataset.key))});
function resize(){const w=container.clientWidth,h=container.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(container);resize();camera.position.set(-3,2,3);const dt=m.opt.timestep;
function step(){const s=getState(m,d,ids);d.ctrl[ids.actuator.drive]=ll.speed(s,state.hatch?0:state.v,dt);d.ctrl[ids.actuator.steer]=ll.steer(s,state.yaw,dt);d.ctrl[ids.actuator.pod_level]=ll.level(s);d.ctrl[ids.actuator.lid]=state.hatch?-1.9:0;mj.mj_step(m,d)}
function frame(t){requestAnimationFrame(frame);const wall=Math.min((t-last)/1000,.05);last=t;elapsed+=wall;
if(!state.paused){state.v=state.hatch?0:(keys.has('ArrowUp')?2:0)+(keys.has('ArrowDown')?-.6:0);state.yaw=(keys.has('ArrowLeft')?.3:0)-(keys.has('ArrowRight')?.3:0);acc+=wall;let steps=0;while(acc>=dt&&steps<25){step();acc-=dt;steps++}if(acc>.1)acc=0}
const s=getState(m,d,ids);state.simTime=d.time;state.actualSpeed=s.v;state.position=s.pos;state.distance+=Math.hypot(s.pos[0]-previous[0],s.pos[1]-previous[1]);previous=s.pos;$('#speed').textContent=Math.abs(s.v).toFixed(2);$('#dist').textContent=state.distance.toFixed(1);mode.textContent=state.paused?'PHYSICS PAUSED':state.hatch?'HATCH OPEN':'MUJOCO TELEOP';renderGeom();const pos=new THREE.Vector3(s.pos[0],s.pos[2],-s.pos[1]);let desired;if(state.camera==='map')desired=pos.clone().add(new THREE.Vector3(0,18,.01));else desired=pos.clone().add(new THREE.Vector3(1.6*Math.cos(s.heading)+2.2*Math.sin(s.heading),1.8,-1.6*Math.sin(s.heading)+2.2*Math.cos(s.heading)));camera.position.lerp(desired,1-Math.exp(-wall*5));camera.lookAt(pos.clone().add(new THREE.Vector3(0,.1,0)));renderer.render(scene,camera)}mission.textContent='Original robot and campus loaded. Hold arrows to drive; release to brake. Space stops, O opens the hatch.';requestAnimationFrame(frame);
}catch(e){mode.textContent='LOAD ERROR';mission.textContent='Physics could not load: '+e.message;$('#error').style.display='grid';console.error(e)}
